<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		<!-- Заголовок и описание страницы -->
		<title><?php echo $pageTitle; ?></title>
		<meta name="description" content="Bla-bla-bla.." />
		
		<!-- Иконка -->
		<link href="./assets/img/favicon.png" rel="icon" type="image/png" />
		
		<!-- Файлы Bootstrap -->
		<link href="./assets/css/bootstrap.css" rel="stylesheet" type="text/css" />
	</head>
	<body>
	
		<!-- Панель навигации -->
		<?php if ($showNavbar): ?>
			<nav class="navbar navbar-inverse">
				<div class="container">
					<div class="navbar-header">
						<a href="./" class="navbar-brand">Планировщик задач</a>
					</div>
					<ul class="nav navbar-nav navbar-right">
						<?php if ($userLoggedIn): ?>
							<li><a><span class="glyphicon glyphicon-user"></span> Вошёл как: <?php echo $currentUser; ?></a></li>
							<li><a href="./signin?action=logout"><span class="glyphicon glyphicon-log-out"></span> Выйти</a></li>
						<?php else: ?>
							<li><a href="./signin"><span class="glyphicon glyphicon-log-in"></span> Войти</a></li>
						<?php endif; ?>
					</ul>
				</div>
			</nav>
		<?php endif; ?>

		<!-- Шапка -->
		<?php if ($showHeader): ?>
			<div class="jumbotron text-center">
				<div class="container">
					<h1>Планировщик задач</h1>
					<p>Тестовое задание для BeeJee</p>
				</div>
			</div>
		<?php endif; ?>

		<!-- Содержимое страницы -->
		<div class="container">
			<?php require('./core/templates/'.$pageContent.'.phtml'); ?>
		</div>
		
		<!-- Пустой отступ -->
		<div style="height:100px;"></div>
		
		<!-- Подвал -->
		<footer>
			<div class="container text-center">
				<p>Копирайт &copy; 2020 все права не защитить.</p>
			</div>
		</footer>
		
		<!-- jQuery и Bootstrap библиотеки -->
		<script src="./assets/js/jquery-3.5.1.js" type="text/javascript"></script>
		<script src="./assets/js/bootstrap.js" type="text/javascript"></script>
	</body>
</html>
