<div class="panel panel-default" style="box-shadow: 0 8px 16px #ccc; margin: 40px auto; max-width: 480px !important;">
	<div class="panel-heading">
		<h2>Форма входа</h2>
	</div>
	<div class="panel-body">
	
		<!-- Уведомление об ошибке -->
		<?php if (isset($userMessage) && ($userMessage != null)): ?>
			<div class="alert alert-danger alert-dismissible" role="alert">
				<button type="button" class="close" data-dismiss="alert"><span>&times;</span></button>
				<?php echo $userMessage; ?> 
			</div>
		<?php endif; ?>
		
		<!-- Форма входа -->
		<form action="./signin?action=signin" method="post">
			<div class="form-group">
				<input type="text" id="inputLogin" name="inputLogin" class="form-control" placeholder="Логин" required autofocus >
			</div>
			<div class="form-group">
				<input type="password" id="inputPassword" name="inputPassword" class="form-control" placeholder="Пароль" required >
			</div>
			<button type="submit" class="btn btn-primary">Войти</button>
		</form>
	</div>
	
	<!-- Подвал панели и кнопка возврата назад -->
	<div class="panel-footer">
		<a href="./" onclick="(function() { if (history.length > 1) history.back(); return false;} )();"><span class="glyphicon glyphicon-arrow-left"></span> Вернуться назад</a>
	</div>
</div>
