<h2>Список имеющихся задач</h2>

<!-- Фильтры сортировки -->
<div class="pull-right">
	<div class="text-right">
		<button class="btn btn-default" data-toggle="collapse" data-target="#filters">Показать фильтры</button>
	</div>
	<div id="filters" class="collapse">
		<hr>
		<form action="./" method="get" class="form-inline">
		
			<!-- Поле "Сортировка по" -->
			<div class="input-group">
				<span class="input-group-addon">Сортировать по:</span>
				<select id="sortby" name="sortby" class="form-control input-sm">
					<option <?php if (isset($listSortBy) && ($listSortBy == 'TaskID')) echo "selected"; ?> value="TaskID">Номеру задачи</option>
					<option <?php if (isset($listSortBy) && ($listSortBy == 'User')) echo "selected"; ?> value="Username">Имени пользователя</option>
					<option <?php if (isset($listSortBy) && ($listSortBy == 'Email')) echo "selected"; ?> value="Email">E-Mail'у</option>
					<option <?php if (isset($listSortBy) && ($listSortBy == 'IsDone')) echo "selected"; ?> value="IsDone">Статусу</option>
				</select>
			</div>
			
			<!-- Поле "Порядок сортировки" -->
			<div class="input-group">
				<span class="input-group-addon">Порядок:</span>
				<select id="orderby" name="orderby" class="form-control input-sm">
					<option <?php if (isset($listOrderBy) && ($listOrderBy == 'DESC')) echo "selected"; ?> value="DESC">По убыванию</option>
					<option <?php if (isset($listOrderBy) && ($listOrderBy == 'ASC')) echo "selected"; ?> value="ASC">По возрастанию</option>
				</select>
			</div>
			<button type="submit" class="btn btn-default input-sm">Применить</button>
		</form>
	</div>
</div>

<!-- Кнопка добавления новой задачи -->
<div class="pull-left">
	<a href="./edit-task" class="btn btn-primary">Добавить новую задачу</a>
</div>

<!-- Очистка 'float' -->
<div class="clearfix"></div>

<hr>

<!-- Таблица со списком задач -->
<table class="table table-hover table-hover table-condensed table-bordered">
	<thead>
		<tr>
			<th class="col-md-1">№</th>
			<th class="col-md-2">Имя пользователя</th>
			<th class="col-md-1">E-Mail</th>
			<th class="col-md-6">Задача</th>
			<th class="col-md-2">Статус</th>
			<?php if ($userLoggedIn): ?>
				<th class="col-md-1">Действия</th>
			<?php endif; ?>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($tasks as $task): ?>
			<tr class="<?php echo $task->isDone ? "success" : "warning" ; ?>">
				<td><?php echo $task->taskId;   ?></td>
				<td><?php echo $task->username; ?></td>
				<td><?php echo $task->email;    ?></td>
				<td><?php echo $task->content;  ?></td>
				<td><?php echo $task->isDone ? "Выполнено" : "Не выполнено" ; ?></td>
				<?php if ($userLoggedIn): ?>
					<td><a href="./edit-task?action=edit&task_id=<?php echo $task->taskId; ?>">Изменить</a></td>
				<?php endif; ?>
			</tr>
		<?php endforeach; ?>
	</tbody>
</table>

<!-- Навигация по страницам таблицы -->
<div class="text-center">
	<ul class="pagination">
		<!-- Вот это, конечно, очень дебильный момент, но я не знаю как сделать по-другому -->
		<?php for ($i = 1; $i <= $totalPages; $i++): ?>
			<li <?php if ($i == $pageNum) echo "class=\"active\""; ?>><a href="./?listPage=<?php echo $i; if (isset($listSortBy)) echo "&sortby=".$listSortBy; if (isset($listOrderBy)) echo "&orderby=".$listOrderBy;?>"><?php echo $i; ?></a></li>
		<?php endfor; ?>
	</ul>
</div>
